[tool.poetry]
name = "music-recommendation-system"
version = "0.1.0"
description = ""
authors = ["Haim <Haim.Michalashvili@lusha.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "3.12.3"
fastapi = "^0.111.0"
uvicorn = "^0.29.0"
SQLAlchemy = "^2.0.30"
pydantic = "^2.7.1"
python-dotenv = "^1.0.1"
pyspark = "3.5.1"
delta-spark = "3.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
